# veja a syntax do github workflows: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-versions: 16.x

      - name: Install dependencies
        run: yarn add

      - name: Linting
        run: yarn lint

      - name: Tests
        run: yarn test

      # há momentos que o dev pode funciona, mas o build não
      - name: Build
        run: yarn build
